"""
PDF report generation for analysis results.

Generates a clean, formatted PDF report containing all analysis data.
Uses fpdf2 for PDF generation — no external system dependencies needed.
Supports Unicode text (Hindi, Tamil, etc.) via built-in DejaVu font.
"""

import logging
import os
from fpdf import FPDF

logger = logging.getLogger(__name__)


def _safe(text) -> str:
    """Ensure text is a string safe for PDF output."""
    if text is None:
        return ""
    return str(text)


class AnalysisReport(FPDF):
    """Custom PDF class for analysis reports with Unicode support."""

    def __init__(self):
        super().__init__()
        # Add DejaVu font for full Unicode support (ships with fpdf2)
        self.add_font("DejaVu", "", os.path.join(os.path.dirname(__file__), "..", "fonts", "DejaVuSansCondensed.ttf"), uni=True)
        self.add_font("DejaVu", "B", os.path.join(os.path.dirname(__file__), "..", "fonts", "DejaVuSansCondensed-Bold.ttf"), uni=True)
        self.add_font("DejaVu", "I", os.path.join(os.path.dirname(__file__), "..", "fonts", "DejaVuSansCondensed-Oblique.ttf"), uni=True)
        self._has_dejavu = True

    def _use_font(self, style="", size=10):
        """Set font with DejaVu (Unicode) fallback to Helvetica."""
        try:
            self.set_font("DejaVu", style, size)
        except Exception:
            self.set_font("Helvetica", style, size)

    def header(self):
        self._use_font("B", 10)
        self.set_text_color(212, 55, 44)
        self.cell(0, 8, "NEWSROOM LENS  |  Bias Analysis Report", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(180, 180, 180)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self._use_font("I", 7)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by Newsroom Lens", align="C")

    def section_title(self, title: str):
        self.ln(3)
        self._use_font("B", 11)
        self.set_text_color(40, 40, 40)
        self.cell(0, 8, _safe(title), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def key_value(self, key: str, value: str):
        self._use_font("B", 9)
        self.set_text_color(100, 100, 100)
        self.cell(50, 6, _safe(key), new_x="RIGHT")
        self._use_font("", 9)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 6, _safe(value), new_x="LMARGIN", new_y="NEXT")

    def body_text(self, text: str):
        self._use_font("", 9)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 5, _safe(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)


def generate_pdf_report(data: dict) -> bytes:
    """Generate a PDF report from analysis results."""
    pdf = AnalysisReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──
    pdf._use_font("B", 16)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 8, _safe(data.get("title", "Untitled Article")), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    if data.get("source_url"):
        pdf._use_font("", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, _safe(data["source_url"])[:120], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # ── Bias Index ──
    pdf.section_title("BIAS ANALYSIS")
    bias = data.get("bias") or {}
    bias_index = bias.get("bias_index", 0) or 0

    pdf._use_font("B", 28)
    if bias_index < 25:
        pdf.set_text_color(30, 124, 74)
    elif bias_index < 50:
        pdf.set_text_color(212, 131, 28)
    elif bias_index < 75:
        pdf.set_text_color(212, 55, 44)
    else:
        pdf.set_text_color(155, 28, 20)
    pdf.cell(30, 14, str(round(bias_index)), new_x="RIGHT")
    pdf._use_font("", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 14, " / 100  Bias Index", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Political leaning
    leaning = bias.get("political_leaning") or {}
    if leaning:
        label = leaning.get("label", "unknown")
        conf = leaning.get("confidence", 0) or 0
        pdf.key_value("Political Leaning:", f"{label} ({round(conf * 100)}% confidence)")

    # Bias types
    bias_types = bias.get("bias_types") or []
    if bias_types:
        top_types = [
            bt for bt in bias_types
            if (bt.get("bias_type", "") or "").lower() not in ["no bias", "unbiased", "none"]
            and (bt.get("confidence", 0) or 0) > 0.10
        ][:6]
        if top_types:
            types_str = ", ".join(
                f"{bt['bias_type']} ({round((bt.get('confidence', 0) or 0) * 100)}%)" for bt in top_types
            )
            pdf.key_value("Detected Types:", types_str)

    # Breakdown
    breakdown = bias.get("bias_breakdown") or {}
    if breakdown:
        pdf.ln(2)
        pdf._use_font("B", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, "Signal Breakdown:", new_x="LMARGIN", new_y="NEXT")
        for k, v in breakdown.items():
            label = k.replace("_", " ").title()
            pdf._use_font("", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(50, 5, f"  {label}:", new_x="RIGHT")
            pdf.cell(0, 5, f"{round(v or 0)}/100", new_x="LMARGIN", new_y="NEXT")

    # ── Summary ──
    summary = data.get("summary") or []
    if summary:
        pdf.section_title("SUMMARY")
        for i, bullet in enumerate(summary):
            pdf._use_font("", 9)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 5, f"  {i+1}. {_safe(bullet)}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    # ── Sentiment ──
    sentiment = data.get("sentiment") or {}
    if sentiment:
        pdf.section_title("SENTIMENT ANALYSIS")
        headline = sentiment.get("headline") or {}
        body = sentiment.get("body") or {}
        pdf.key_value("Headline:", f"{headline.get('label', 'N/A')} ({round((headline.get('score', 0) or 0) * 100)}%)")
        pdf.key_value("Body:", f"{body.get('label', 'N/A')} ({round((body.get('score', 0) or 0) * 100)}%)")
        pdf.key_value("Sentiment Gap:", f"{round((sentiment.get('sentiment_gap', 0) or 0) * 100)}%")
        if sentiment.get("sensationalism_flag"):
            pdf._use_font("B", 9)
            pdf.set_text_color(212, 131, 28)
            pdf.cell(0, 6, "  SENSATIONALISM FLAG: Headline tone differs significantly from body", new_x="LMARGIN", new_y="NEXT")

    # ── Source Credibility ──
    cred = data.get("source_credibility")
    if cred and isinstance(cred, dict) and cred.get("known"):
        pdf.section_title("SOURCE CREDIBILITY")
        pdf.key_value("Domain:", _safe(cred.get("domain", "unknown")))
        pdf.key_value("Reliability:", f"{cred.get('reliability_score', 'N/A')}/100")
        pdf.key_value("Factual Reporting:", _safe(cred.get("factual_reporting", "N/A")))
        pdf.key_value("Bias Rating:", _safe(cred.get("bias_rating", "N/A")))
        pdf.key_value("Category:", _safe(cred.get("category", "N/A")))
        if cred.get("description"):
            pdf.body_text(cred["description"])

    # ── Claim Verification ──
    claims = data.get("claims") or []
    if claims:
        pdf.section_title("CLAIM VERIFICATION")
        for c in claims:
            if not isinstance(c, dict):
                continue
            verdict = (c.get("verdict") or "unknown").upper()
            claim_text = _safe(c.get("claim", ""))
            explanation = _safe(c.get("explanation", ""))

            if verdict == "VERIFIED":
                pdf.set_text_color(30, 124, 74)
            elif verdict == "MISLEADING":
                pdf.set_text_color(212, 55, 44)
            elif verdict == "OPINION":
                pdf.set_text_color(139, 92, 246)
            else:
                pdf.set_text_color(212, 131, 28)

            pdf._use_font("B", 9)
            pdf.cell(28, 5, f"  [{verdict}]", new_x="RIGHT")
            pdf.set_text_color(50, 50, 50)
            pdf._use_font("", 9)
            pdf.multi_cell(0, 5, claim_text, new_x="LMARGIN", new_y="NEXT")
            if explanation:
                pdf.set_text_color(120, 120, 120)
                pdf._use_font("I", 8)
                pdf.multi_cell(0, 4, f"    {explanation}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

    # ── Evidence ──
    evidence = bias.get("evidence") or []
    if evidence:
        pdf.section_title("BIAS EVIDENCE")
        for ev in evidence[:5]:
            if not isinstance(ev, dict):
                continue
            sentence = _safe(ev.get("sentence", ""))
            bias_type = _safe(ev.get("bias_type", ""))
            conf = ev.get("confidence", 0) or 0

            pdf._use_font("B", 8)
            pdf.set_text_color(212, 55, 44)
            pdf.cell(0, 5, f"  {bias_type} ({round(conf * 100)}%)", new_x="LMARGIN", new_y="NEXT")
            pdf._use_font("I", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 4, f'  "{sentence}"', new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

    # ── Neutral Rewrites ──
    rewrites = data.get("neutral_rewrites") or []
    if rewrites:
        pdf.section_title("NEUTRAL REWRITES")
        for rw in rewrites:
            if not isinstance(rw, dict):
                continue
            original = _safe(rw.get("original", ""))
            neutral = _safe(rw.get("neutral", ""))

            pdf._use_font("B", 8)
            pdf.set_text_color(212, 55, 44)
            pdf.cell(18, 5, "  Original:", new_x="RIGHT")
            pdf._use_font("", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 4, original, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

            pdf._use_font("B", 8)
            pdf.set_text_color(30, 124, 74)
            pdf.cell(18, 5, "  Neutral:", new_x="RIGHT")
            pdf._use_font("", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 4, neutral, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)

    # Output — fpdf2 returns bytearray, convert to bytes
    return bytes(pdf.output())
